---
title: "sec_ass"
format: html
editor: visual
---

```{r}
#| setup
#| echo: false
#| output: false
#| message: false
library (vtable)
library(tidyverse)
library(ggplot2)
library(tinytex)
library(ggpubr)
```

```{r}
hoyde <- modelr::heights
hoyde <- hoyde |>
  mutate(
    bmi = weight * 0.4536/(height * 2.54/100)^2,
    married = fct_collapse(
      .f = marital,
      married = "married",
      other_level = "not married"
      ),
    edu_fac = cut(
      x = education,
      breaks = c(0, 12, 14, 16, 21),
      labels = c("not_hs", "not_cc", "not_col", "col_plus"),
      right = FALSE
      )
    ) |>
  select(income:age, education:bmi, everything()) |>
  select(-education, -marital)
hoydeZeroInc <- hoyde |>
  filter(income == 0)
hoydeNormInc <- hoyde |>
  filter(income > 0 & income < 343830)
hoydeHighInc <- hoyde |>
  filter(income == 343830)
```

## Innledning

## Litteraturgjennomgang

## Sammenheng mellom inntekt og evnenivå

```{r}
#sammenheng mellom afqt og inntekt i hoydeNormInc
hoydeNormInc |>
  ggplot(mapping = aes(x = afqt, y = income)) +
  geom_point() +
  geom_smooth()
```

```{r}
#afqt i hoydeZeroInc og hoydeHighInc
ggplot(
  data = hoydeZeroInc
  )+
  geom_histogram(
    mapping = aes(x = afqt, y = after_stat(density)),
    alpha = 0.3,
    colour = "blue",
    fill = "blue")+
  geom_histogram(
    data = hoydeHighInc,
    mapping = aes(x = afqt, y = after_stat(density)),
    alpha = 0.5,
    colour = "red",
    fill = "red"
  )
```

```{r}
#sammenheng mellom afqt og inntekt, facet mht. kjønn
ggplot(hoyde) +
  geom_point(
    mapping = aes(x = afqt, y = income)) +
  geom_smooth()
```

```{r}
#sammenheng mellom edu_fac/education og afqt
ggplot(
  data = hoyde,
  mapping = aes(
    x = edu_fac,
    y = afqt
  )
) +
  geom_point()
```

```{r}
#sammenheng mellom høyde og afqt
hoyde |>
  select(afqt, height) |>
  ggplot(mapping = aes(x = afqt, y = height)) +
  geom_point() +
  geom_smooth()
```

```{r}
# sammenligner afqt kvinner og menn på hele datasettet (ekstra) 
hoyde |>
  ggplot() +
  geom_histogram(
    data = filter(hoyde, sex == "male"),
    mapping = aes(x = afqt, y = after_stat(density)),
    alpha = 0.3,
    colour = "blue",
    fill = "blue"
  ) + 
  geom_histogram(
    data = filter(hoyde, sex == "female"),
    mapping = aes(x = afqt, y = after_stat(density)),
    alpha = 0.5,
    colour = "red",
    fill = "red"
  )
```

## Sammenheng mellom ansiennitet og inntekt

## Konklusjon

## Referanser
